name: Merge Rules

on:
  schedule:
    - cron: '0 23 * * *' # 每天早上7点触发
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  merge_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear *.txt
        run: |
          echo "" > DS_direct.txt
          echo "" > DS_proxy.txt
          echo "" > ip_cncidr.txt
          echo "" > reject.txt

      - name: Merge rules
        run: |
          curl -L https://raw.githubusercontent.com/jioyla/surge_rules/main/my_rule-set_direct.txt >> DS_direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/private.txt >> DS_direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt >> DS_direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt >> DS_direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/icloud.txt >> DS_direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/google.txt >> DS_direct.txt
          curl -L https://raw.githubusercontent.com/jioyla/surge_rules/release/my_proxy.txt >> DS_proxy.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt >> DS_proxy.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/tld-not-cn.txt >> DS_proxy.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/gfw.txt >> DS_proxy.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt >> ip_cncidr.txt
          curl -L https://ruleset.skk.moe/List/domainset/reject.conf >> reject.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/reject.txt >> reject.txt

      - name: Sync cncidr.txt
        run: |
          sed -i 's/$/,no-resolve/' ip_cncidr.txt
          sed -i '1d' ip_cncidr.txt
          sort -u DS_direct.txt -o DS_direct.txt 
          sort -u DS_proxy.txt -o DS_proxy.txt
          sort -u ip_cncidr.txt -o ip_cncidr.txt
          sort -u reject.txt -o reject.txt
          curl -L https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/ASN.China.list >> ip_cncidr.txt
          
      - name: Commit and push changes
        uses: fregante/setup-git-user@v2
      - run: |
          git init
          git checkout -b release
          git add DS_direct.txt ip_cncidr.txt DS_proxy.txt reject.txt
          git commit -m "Merge rules"
          git push -f -u origin release
