name: Sync cncidr.txt

on:
  schedule:
    - cron: '0 7 * * *' # 每天早上7点更新
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Download cncidr.txt
        run: |
          curl -O -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt

      - name: Sync cncidr.txt
        run: |
          sed -i 's/$/.no-resolve/' cncidr.txt
          
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      # - run: git stash
      - run: git pull origin main
      # - run: git stash apply
      - run: git add .
      - run: git commit --message 'Sync cncidr.txt'
      - run: git push
