name: Direct Rules

on:
  schedule:
    - cron: '0 23 * * *' # 这里是UTC时区，+8 才是中国时间
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  merge_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge rules
        run: |
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/private.txt >> direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt >> direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt >> direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/icloud.txt >> direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/google.txt >> direct.txt
          sed -i '' -e '/^$/d' direct.txt # 删除空行
          awk '!seen[$0]++' direct.txt > direct_tmp.txt && mv direct_tmp.txt direct.txt # 删除重复行
          sed -i '' -e 's/$/,no-resolve/' direct.txt # 在每行末尾加上",no-resolve"
          git add direct.txt
          git commit -m "Direct rules"
          git push origin release
