name: Sync cncidr.txt

on:
  schedule:
    - cron: '0 7 * * *' # 每天早上7点更新
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Download cncidr.txt
        run: |
          curl -O -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt

      - name: Sync cncidr.txt
        run: |
          sed -i 's/$/.no-resolve/' cncidr.txt
          
      - name: Commit and push changes
        run: |
          git config --global user.name "jioyla"
          git config --global user.email "lz4261@gmail.com"
          # git stash
          # git pull origin main
          # git stash apply
          git add cncidr.txt
          git commit -m "Sync cncidr.txt"
          git push
