name: Direct Rules

on:
  schedule:
    - cron: '0 23 * * *' # 每天早上7点触发
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  merge_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear direct.txt
        run: echo "" > direct.txt

      - name: Merge rules
        run: |
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/private.txt >> direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt >> direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt >> direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/icloud.txt >> direct.txt
          curl -L https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/google.txt >> direct.txt
          cat direct.txt | sort | uniq | sed 's/$/,no-resolve/' > direct.txt
      
      - name: Commit and push changes
        uses: fregante/setup-git-user@v2
      - run: |
          git init
          git checkout -b release
          git add direct.txt
          git commit -m "Direct rules"
          git push -f -u origin release
